services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
  backend:
    restart: unless-stopped
    depends_on:
      - database
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3333"

